import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api.js";

const CATEGORY_STYLE = {
  "High Intent": "bg-emerald-100 text-emerald-700",
  "Medium Intent": "bg-amber-100 text-amber-700",
  "Low Intent": "bg-slate-200 text-slate-600",
};

// Circular score meter drawn with SVG.
function ScoreRing({ score }) {
  const r = 52;
  const c = 2 * Math.PI * r;
  const color = score >= 75 ? "#10b981" : score >= 50 ? "#f59e0b" : "#94a3b8";
  return (
    <svg width="130" height="130" viewBox="0 0 130 130" role="img" aria-label={`Lead score ${score} out of 100`}>
      <circle cx="65" cy="65" r={r} fill="none" stroke="#e2e8f0" strokeWidth="12" />
      <circle
        cx="65" cy="65" r={r} fill="none" stroke={color} strokeWidth="12" strokeLinecap="round"
        strokeDasharray={c} strokeDashoffset={c * (1 - score / 100)} transform="rotate(-90 65 65)"
      />
      <text x="65" y="63" textAnchor="middle" className="fill-slate-900 text-3xl font-extrabold">{score}</text>
      <text x="65" y="84" textAnchor="middle" className="fill-slate-500 text-xs">out of 100</text>
    </svg>
  );
}

function CopyButton({ text, label = "Copy" }) {
  const [done, setDone] = useState(false);
  return (
    <button
      className="btn-ghost"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setDone(true);
          setTimeout(() => setDone(false), 1500);
        } catch { /* clipboard blocked - ignore */ }
      }}
    >
      {done ? "Copied ✓" : label}
    </button>
  );
}

export default function Welcome() {
  const { id } = useParams();
  const [s, setS] = useState(null);
  const [error, setError] = useState("");
  const [tab, setTab] = useState("whatsapp");

  useEffect(() => {
    api.student(id).then(setS).catch((e) => setError(e.message));
  }, [id]);

  if (error) return <div className="mx-auto max-w-xl p-10 text-center text-red-600">{error}</div>;
  if (!s) return <div className="p-10 text-center text-slate-500">Loading your AI plan…</div>;

  const first = s.name.split(" ")[0];
  const shareText = `I just registered for NxtWave's free "Build Your First AI Project in 60 Minutes" workshop. Join me: ${s.referral_link}`;

  return (
    <main className="mx-auto max-w-5xl px-4 py-10">
      <div className="text-center">
        <div className="text-5xl">🎉</div>
        <h1 className="mt-3 text-3xl font-extrabold text-slate-900">You're in, {first}!</h1>
        <p className="mt-2 text-slate-600">
          Your seat is reserved. Here is the AI analysis of your profile.
          <span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-500">
            {s.ai_source === "gemini" ? "Generated by Gemini" : "AI simulation mode"}
          </span>
        </p>
      </div>

      <div className="mt-10 grid gap-6 md:grid-cols-3">
        {/* PERSONA */}
        <section className="card md:col-span-2">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-brand-600">Your student persona</h2>
          <dl className="mt-4 space-y-4">
            <div><dt className="text-xs font-semibold uppercase text-slate-400">Name</dt><dd className="font-semibold">{s.name}</dd></div>
            <div><dt className="text-xs font-semibold uppercase text-slate-400">Profile</dt><dd>{s.persona?.profile}</dd></div>
            <div><dt className="text-xs font-semibold uppercase text-slate-400">Pain point</dt><dd>{s.persona?.pain_point}</dd></div>
            <div><dt className="text-xs font-semibold uppercase text-slate-400">Motivation</dt><dd>{s.persona?.motivation}</dd></div>
          </dl>
        </section>

        {/* SCORE */}
        <section className="card flex flex-col items-center text-center">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-brand-600">Workshop fit score</h2>
          <div className="mt-3"><ScoreRing score={s.score} /></div>
          <span className={`mt-3 rounded-full px-3 py-1 text-sm font-semibold ${CATEGORY_STYLE[s.category]}`}>{s.category}</span>
          <p className="mt-3 text-sm text-slate-600">{s.score_reason}</p>
        </section>

        {/* OUTREACH */}
        <section className="card md:col-span-2">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-semibold uppercase tracking-wide text-brand-600">Your personalised message</h2>
            <div className="flex gap-1 rounded-lg bg-slate-100 p-1 text-sm">
              {["whatsapp", "email"].map((t) => (
                <button key={t} onClick={() => setTab(t)}
                  className={`rounded-md px-3 py-1 font-medium capitalize ${tab === t ? "bg-white shadow" : "text-slate-500"}`}>
                  {t}
                </button>
              ))}
            </div>
          </div>
          {tab === "whatsapp" ? (
            <pre className="mt-4 whitespace-pre-wrap rounded-xl bg-emerald-50 p-4 font-sans text-sm text-slate-800">{s.outreach?.whatsapp}</pre>
          ) : (
            <div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm">
              <div className="font-semibold">Subject: {s.outreach?.email_subject}</div>
              <pre className="mt-2 whitespace-pre-wrap font-sans text-slate-800">{s.outreach?.email_body}</pre>
            </div>
          )}
          <div className="mt-3">
            <CopyButton text={tab === "whatsapp" ? s.outreach?.whatsapp : s.outreach?.email_body} />
          </div>
        </section>

        {/* REFERRAL */}
        <section className="card">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-brand-600">Become a college ambassador</h2>
          <p className="mt-2 text-sm text-slate-600">Invite friends. Top referrers are featured on the leaderboard.</p>
          <div className="mt-4 rounded-xl border-2 border-dashed border-brand-500 bg-brand-50 p-3 text-center">
            <div className="text-xs text-slate-500">Your referral code</div>
            <div className="text-xl font-extrabold tracking-wider text-brand-700">{s.referral_code}</div>
          </div>
          <div className="mt-3 grid grid-cols-2 gap-2">
            <CopyButton text={s.referral_link} label="Copy link" />
            <a className="btn-ghost" target="_blank" rel="noreferrer" href={`https://wa.me/?text=${encodeURIComponent(shareText)}`}>
              Share on WhatsApp
            </a>
          </div>
          <div className="mt-4 flex justify-between text-sm">
            <span className="text-slate-500">Friends joined</span>
            <b>{s.referral_count}</b>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">Your rank</span>
            <b>{s.rank ? `#${s.rank}` : "Invite 1 friend to rank"}</b>
          </div>
          <Link to="/leaderboard" className="mt-4 block text-center text-sm font-medium text-brand-600 hover:underline">View leaderboard →</Link>
        </section>
      </div>
    </main>
  );
}
